### ISSUE TITLE
Not working on IE9

### ISSUE THREAD

**Issue by israelsaraiva** [tihomir-kit/angular-net-async-upload#2]
HI! I have tested on IE9, then give me the following error:
SCRIPT438: O objeto não oferece suporte à propriedade ou método 'getFiles'  (the object do not offer suport to property or method 'getFiles')
angular-file-upload-shim.js, line 153 Caracter 4

**Comment by tihomir-kit** [comment]
Hi,

I don't remember well, but yes, I believe this was not supported by IE9 back then when I made the demo. Perhaps to see if there's a newer shim on [angular-file-upload](https://github.com/danialfarid/ng-file-upload).. That part of code is actually a 3rd party JS library so if it doesn't support IE9, I can't really do much about it unfortunately.

And in general, this codebase is now quite stale, the ng-upload directive was updated since then and probably has a newer API, so you might want to rewrite some things. This was just a showcase to shorten the time for other developers if they ever need to implement this kind of upload.

**Comment by tihomir-kit** [comment]
No reply and not really related to the repo, closing.
